# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cruziken
email: partimecruz8@gmail.com
description:
  Trying to figure everything out
cover: assets/images/universe.jpg
logo: assets/images/universe.png
favicon: assets/images/favicon.png
baseurl: "/home/" # the subpath of your site, e.g. /blog
url: "http://cruziken.com" # the base hostname & protocol for your site, e.g. http://example.com
# Social
twitter_username: not available
github_username:  cruziken

#Additional Pages
about: about
forge: forge
poetry: poetry


permalink: /:title

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


#Settings for rake task
safe: False
lsi: False
username: cruziken #github username
repo: cruziken.github.io #github repository
branch: master #branch
relative_source: ../cruziken.github.io/ #source directory
destination: ../cruziken.github.io/ #destination directory
production_url:  https://cruziken.com/
source_url:  https://github.com/Cruziken/cruziken.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
